### ISSUE TITLE
env issue - npm run start keeps running dev environment?

### ISSUE THREAD

**Issue by donjae** [jeffijoe/koa-es7-boilerplate#11]
Hey jeffi, long time no see xD

About to deploy my app and having issues trying to run it in prod. When I run npm run start (`node dist/bin/server.js`), it keeps running it in development mode. Any clue what I need to do?

**Comment by jeffijoe** [comment]
Did you set NODE_ENV=production?

**Comment by donjae** [comment]
so in `src/lib/env.js`? i.e: `NODE_ENV: process.env.NODE_ENV || 'production',`

Tried setting it to `NODE_ENV: 'production'`, and notice console is saying that: 

`DEBUG Server listening on 1338 in production mode (/Users/datboi/programming/working-projects/koa-es7/dist/bin/server.js:22)`

So it's still running on the wrong port. so set server.js `const PORT = env.PORT || 1338` to `80`?

**Comment by jeffijoe** [comment]
That uses the envs NODE_ENV, you should use

NODE_ENV=production npm start

Regards,
Jeff Hansen

On 29 Apr 2017, 17.39 +0200, donjae <notifications@github.com>, wrote:

so in src/lib/env.js? i.e: NODE_ENV: process.env.NODE_ENV || 'production',

(then run build)

**Comment by donjae** [comment]
@jeffijoe thanks fam. makes way more sense
