### ISSUE TITLE
this is undefined

### ISSUE THREAD

**Issue by ytianzaishui** [jeffijoe/koa-es7-boilerplate#14]
![image](https://user-images.githubusercontent.com/18025841/36088085-9c63c7ec-1010-11e8-8257-df71bfa9ac0a.png)

![image](https://user-images.githubusercontent.com/18025841/36088111-b228ecba-1010-11e8-8646-2b53055ef557.png)

I learn from u proj , why i cant find this ? thankU

**Comment by jeffijoe** [comment]
Well `this` is probably undefined because `Login` is static.

I'm not sure how this is related to the boilerplate?

**Comment by ytianzaishui** [comment]
no related , but i get some idea from U project , how can i do to log this , or instant and use guessPosition Correctly, thank U

**Comment by jeffijoe** [comment]
Remove `static`.

**Comment by Chen-WeiZhen** [comment]
of cause I remove `static` but also `undefined`

is there I forgot something ?
![image](https://user-images.githubusercontent.com/18025841/36088682-2b93c258-1013-11e8-9279-a5abe3fee038.png)
![image](https://user-images.githubusercontent.com/18025841/36088686-2eeb3d50-1013-11e8-8245-2bfde5116087.png)
![image](https://user-images.githubusercontent.com/18025841/36088690-34e6fe2e-1013-11e8-86f0-8df34fe5954d.png)

ok , now just `console.log(this.tencentkey)` but `undefined`

**Comment by ytianzaishui** [comment]
I get it , remove `static` is first , second I  need to use `bind` in children's `constructor`

**Comment by jeffijoe** [comment]
That depends on how you use it. Are you invoking it directly or are you passing a ref to the function? I don't have enough context to help you.
