### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by eldad87** [jeffijoe/koa-es7-boilerplate#15]
I really liked the work done in the project, Its definitely one of the most interesting boilerplates out there. Unfortunately, there is a major draw back - which is lack of documentation. Not project documentation, but auto generated API documentation, something like Swagger, apidoc etc.

So my request is simple, if possible, please advise on how to integrate a tool like Swagger.
Thanks!

**Comment by jeffijoe** [comment]
I'm not a big fan of any of the API documentation tools (yet) so I wouldn't know how to set that up. This is a boilerplate though, so you're free to fork it and make changes. 😄
