### ISSUE TITLE
An automatic line change Function

### ISSUE THREAD

**Issue by Leekyungun** [jeffijoe/koa-es7-boilerplate#16]
Hi, I use your boilerplate. 

When I was commit, source code lines change automatic.

ex) 
![image](https://user-images.githubusercontent.com/12290390/42300641-6772944e-804c-11e8-9672-d083b3138fe0.png)

I want to my code line T. T

package.json File.
![image](https://user-images.githubusercontent.com/12290390/42300666-864c93ba-804c-11e8-88c1-eff25254e59a.png)
![image](https://user-images.githubusercontent.com/12290390/42300671-8cf8aabe-804c-11e8-9fc9-7835791cc41a.png)

help me~

**Comment by jeffijoe** [comment]
If you want to disable this behavior, you need to remove `prettier` from the `lint` scripts. I think it's great though, it keeps your code style consistent.

Alternatively, you can change the column setting (default is 80) so it keeps your lines smaller. https://prettier.io/

**Comment by Leekyungun** [comment]
Thank you~!

I modified this part.  ( del "prettier --write",)

![image](https://user-images.githubusercontent.com/12290390/42307322-f9ea720e-806c-11e8-9607-1b7c8684081e.png)
