### ISSUE TITLE
How to generate Swagger api for KOA Awilix router core

### ISSUE THREAD

**Issue by cherukurisurendra2010** [jeffijoe/koa-es7-boilerplate#19]
Hi Jeffijoe,

Greetings of the day... !!!

We are trying to generate the Swagger api for the repository to expose the apis.

Could you please suggest what are the changes we need to consider for this.

Thanks

**Comment by jeffijoe** [comment]
Hi there!

I never used Swagger, so I have no idea. 😄

**Comment by cherukurisurendra2010** [comment]
Thank you very much for the quick reply Joe...

Or is there any input to generate the document like swagger api with this repository

**Comment by jeffijoe** [comment]
There's nothing in this repository related to Swagger.

**Comment by cherukurisurendra2010** [comment]
Hi Jeff,

is there any way to export all the api's as single json for the application.

Thanks,
Surendra.

**Comment by jeffijoe** [comment]
Not built-in, that's something you have to bring yourself. 😄
