### ISSUE TITLE
How can we access one service function in another service class

### ISSUE THREAD

**Issue by cherukurisurendra2010** [jeffijoe/koa-es7-boilerplate#20]
Hi Joe,

Greetings of the day...!!!

We have created some generic service and we would like call the another service class function in this service.

and all services are registered under loaded under scoped.

When we are trying to loadthe service in the constructor function and using the same in our function getting below error.

→  TypeError: Cannot read property 'apply' of undefined
    →      at memberInvoker (D:\UI\Projects\koa-abs\node_modules\awilix-koa\src\invokers.ts:93:38)
    →      at dispatch (D:\UI\Projects\koa-abs\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    →      at next (D:\UI\Projects\koa-abs\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    →      at D:\UI\Projects\koa-abs\node_modules\koa-router\lib\router.js:346:16
    →      at dispatch (D:\UI\Projects\koa-abs\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    →      at D:\UI\Projects\koa-abs\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    →      at dispatch (D:\UI\Projects\koa-abs\node_modules\koa-router\lib\router.js:351:31)
    →      at dispatch (D:\UI\Projects\koa-abs\node_modules\koa-compose\index.js:42:32)
    →      at D:\UI\Projects\koa-abs\node_modules\koa-compose\index.js:34:12
    →      at dispatch (D:\UI\Projects\koa-abs\node_modules\koa-compose\index.js:42:32)
    →      at scopePerRequestMiddleware (D:\UI\Projects\koa-abs\node_modules\awilix-koa\src\scope-per-request.ts:13:12)
    →      at dispatch (D:\UI\Projects\koa-abs\node_modules\koa-compose\index.js:42:32)
    →      at bodyParser (D:\UI\Projects\koa-abs\node_modules\koa-bodyparser\index.js:86:11)
    →      at <anonymous>
    →      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Could you please provide any help in this regard.

**Comment by jeffijoe** [comment]
My name is Jeff. ;)

Please show me the code for the route file.

**Comment by cherukurisurendra2010** [comment]
Sorry for the wrong mention for your name. :)

and here the code we are using in routes

import { createController } from 'awilix-koa'

const api = genericService => ({
  previewData: async ctx =>
    ctx.ok(await genericService.previewData(ctx))
})

export default createController(api)
  .prefix('/generic')
  .post('/previewData', 'previewData')

**Comment by jeffijoe** [comment]
The error occurs because it is attempting to call a function that does not exist. But according to your code above it should work fine. Are you sure this is the route you are hitting that produces the error?

**Comment by cherukurisurendra2010** [comment]
Thank you for the update Jeff... :)

In Router file we can include multiple services and we can can call any service function.

Just for request:
is there any way that i can use the one service(services/a-service.js) in another service like (services/b-service.js).

will we use a-service function available in b-service.js

Thanks,
Surendra.

**Comment by jeffijoe** [comment]
Yes you can, simply declare it in `service-b` constructor. 😄 

Is this issue resolved? 😄
