### ISSUE TITLE
How to implement a MongoDB store

### ISSUE THREAD

**Issue by brianupskill** [jeffijoe/koa-es7-boilerplate#21]
HI Jeff, 

I'm trying to replace your in-memory todoStore with a simple MongoDB data store. I am trying to create a 'Device' service that would deal with devices endpoint and interact with the 'devices' collection inside my 'app' database in MongoDB.

Here's my code so far:

`routes/device.js`
```
const { createController } = require('awilix-koa')

const api = deviceService => ({
  createTodo: async ctx => ctx.ok(await deviceService.create(ctx.request.body))
})

exports.default = createController(api)
  .prefix('/device')
  .post('', 'createDevice')
```
`services/deviceService.js`
```
const { BadRequest } = require('fejl')

class DeviceService {
  constructor(deviceStore, logger) {
    this.logger = logger
    this.deviceStore = db
  }
  async createDevice(data) {
    BadRequest.assert(data, 'No device payload given')
    this.deviceStore.connect()
    return this.deviceStore.create(data)
  }
}

module.exports = DeviceService
```

`store/deviceStore`
```
const MongoClient = require('mongodb').MongoClient

class deviceStore {
  constructor(logger) {
    this.logger = logger
  }
  async connect() {
    if (!this.db) {
      const db = await MongoClient.connect('mongoURL')
      this.db = db
    }
    this.collection = this.db.collection('devices')
  }

  async close() {
    if (this.db) {
      try {
        const close = await this.db.close()
      } catch (err) {
        this.logger.error(`Failed to close the database: ${err.message}`)
      }
    }
  }

  async create(data) {
    try {
      const insert = await this.collection.inserMany(data)
    } catch (err) {
      this.logger.error('Error inserting to MongoDB')
    }
  }
}

module.exports = deviceStore
```

1) How/when to call connect? I ideally want the connect to happen on the constructor, but the constructor doesn't support promises. I would ideally want something like this: 
``` 
  constructor(logger) {
    this.logger = logger
    const db = await MongoClient.connect('mongoURL')
    this.collection = this.db.collection('devices')
  }
``` 

So that when awilix calls `new` on the deviceStore, it connects immediately and I don't have to call deviceStore.connect() on each call to the MongoDB collection.

2) When to call close? I'm unsure where to place the closing of the connection to Mongo.

**Comment by jeffijoe** [comment]
Ideally you would use a client that does not use async connect calls. For example, many db clients manages the connection for you, giving you the illusion that connecting happens sync in the constructor.

For your case I would recommend connecting in the configureContainer, register it in the container asFunction that just returns your instance, and use the disposer feature to close it.

Makes sense?

**Comment by brianupskill** [comment]
Perfect. Thanks.
