### ISSUE TITLE
what's the best way to add route middlewares?

### ISSUE THREAD

**Issue by brianupskill** [jeffijoe/koa-es7-boilerplate#25]
Hi Jeff, 

I am wondering what would be the best route (punt intended) to integrate different types of middlewares? More specifically, how would I approach design so that I have:

- One middleware applied to all routes in my app.
- One middleware applied to all routes in my app under a prefix. 
- One middleware to all GET functions across all my routes.
- One middleware to one specific route.

**Comment by jeffijoe** [comment]
1. app.use
2, 3: wrap the middleware in a function that checks whatever you want checked
4. Use the `before` hook from awilix-koa

Hope this helps 😀
