### ISSUE TITLE
Trouble when deploy to heroku

### ISSUE THREAD

**Issue by ghost** [jeffijoe/koa-es7-boilerplate#26]
Hi, I have used this boilerplate to build 2 apis and love it so much. However, I am not able to deploy to heroku. It returns this error all the time.

![capture](https://user-images.githubusercontent.com/13108786/51450870-0f78fb00-1d65-11e9-8e30-95ffd34d5e00.PNG)

I did try to install source-map or source-map/register by using Heroku's console but it does not work. My deploy method is using GitHub and I already push the folder "dist" to GitHub but doesn't change anything.

**Comment by jeffijoe** [comment]
Does it work anywhere else? How about `npm install --save source-map-support`?

Also keep in mind you need to push the package.json as well + run `npm install` in production.

**Comment by ghost** [comment]
It does work in local environment. Here is my package.json, hope it could help.

package.json

<img width="601" alt="screen shot 2019-01-21 at 5 18 59 pm" src="https://user-images.githubusercontent.com/13108786/51468135-ca72ba00-1da0-11e9-9919-6609a8679d74.png">

Procfile

<img width="300" alt="screen shot 2019-01-21 at 5 19 08 pm" src="https://user-images.githubusercontent.com/13108786/51468140-cf376e00-1da0-11e9-8ff4-0f34d8096e18.png">

**Comment by jeffijoe** [comment]
Then it seems that Heroku is not calling `npm install`? I've never used Heroku.

**Comment by ghost** [comment]
So, what is your favorite hosting method ? I need to do it so bad.

**Comment by jeffijoe** [comment]
You should be able to get it to work on Heroku, maybe you are missing something?

I prefer Kubernetes. 😄

**Comment by ghost** [comment]
So, it appears that Heroku skip to install the dev dependencies (rimraf, babel, ...) and it leads to cause my error. In order to fix that, I have to set the NPM_CONFIG_PRODUCTION to false. There are 2 ways to do it.

1. Use Heroku CLI : `heroku config:set NPM_CONFIG_PRODUCTION=false`
2. Use Heroku management console > tab Settings > Config Vars
<img width="1280" alt="screen shot 2019-01-21 at 11 38 28 pm" src="https://user-images.githubusercontent.com/13108786/51487730-55ba7280-1dd6-11e9-81c9-ebba851dda26.png">

**Comment by jeffijoe** [comment]
Might be a good idea to add `source-map-support` under `dependencies`, that should work, too.
