### ISSUE TITLE
Use new ECMAScript modules

### ISSUE THREAD

**Issue by unixfox** [jeffijoe/koa-es7-boilerplate#28]
I would like to remove the babel dependency and use the new ECMAScript modules support but it seems like a hard task.

What I did:
1. I added `"type": "module"` in the `package.json`.
2. I added `.js` for every file import. An example:

```
import { logger } from './logger'
```

into:
```
import { logger } from './logger.js'
```

3. For every file that use `__dirname` variable I added this code:

```js
import { fileURLToPath } from 'url';
import { dirname } from 'path';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
```
like suggested here: https://nodejs.org/api/esm.html#esm_no_require_exports_module_exports_filename_dirname

4. For the awilix-router-core npm module I tried to use import like suggested here: https://github.com/jeffijoe/awilix-router-core/issues/6
5. I got stuck on an error related to `require` in the awilix npm module (https://github.com/jeffijoe/awilix/blob/master/src/container.ts#L584) and now I don't know what to do.

Can someone help me about that?

**Comment by jeffijoe** [comment]
Awilix depends on `require`. If you want, you can pass in your own require function via the options parameter.

Or don't use `loadModules`.

**Comment by unixfox** [comment]
@jeffijoe Thank you for your help!

Based on your help I tried to convert the code into ESM compatible here: https://github.com/unixfox/koa-es7-boilerplate

My changes are located in this commit: https://github.com/unixfox/koa-es7-boilerplate/commit/236d2a8802388f599686c7a8a01ea89c97052285

Unfortunately one error remains and related to not finding the todoService when browsing the URL http://localhost:5000/todos:
```
  16:27:45:793 DEBUG Creating server... (src/lib/server.js:24)
  16:27:45:801 DEBUG startup Server created, ready to listen (src/lib/server.js:61)
  16:27:45:804 DEBUG Server listening on 5000 in development mode (src/bin/www.js:9)
  16:27:49:298 ERROR Error in request (src/middleware/error-handler.js:20)
    →  AwilixResolutionError: Could not resolve 'todoService'.
    →  
    →  Resolution path: todoService
    →      at resolve (/tmp/koa-es7-boilerplate/node_modules/awilix/lib/container.js:239:23)
    →      at /tmp/koa-es7-boilerplate/node_modules/awilix/lib/resolvers.js:302:54
    →      at Array.map (<anonymous>)
    →      at Object.resolve (/tmp/koa-es7-boilerplate/node_modules/awilix/lib/resolvers.js:302:43)
    →      at Object.build (/tmp/koa-es7-boilerplate/node_modules/awilix/lib/container.js:312:37)
    →      at memberInvoker (/tmp/koa-es7-boilerplate/node_modules/awilix-koa/lib/invokers.js:83:38)
    →      at dispatch (/tmp/koa-es7-boilerplate/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    →      at next (/tmp/koa-es7-boilerplate/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    →      at /tmp/koa-es7-boilerplate/node_modules/koa-router/lib/router.js:346:16
    →      at dispatch (/tmp/koa-es7-boilerplate/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
```

Do you think you could take a look at my changes and give me some hints on how to resolve this error?

The command for executing the project is `node src/bin/www.js` or `npm start`. You need to use NodeJS 14+.

**Comment by jeffijoe** [comment]
You can't make `require` async, you need to register the services and stores manually.

**Comment by unixfox** [comment]
> You can't make `require` async, you need to register the services and stores manually.

I should stop using `loadModules` and register each services and store in a new container then? Like it is somewhat described in the `index.js` here: https://github.com/jeffijoe/awilix#inlining-resolver-options?

EDIT: I just updated my repo (https://github.com/unixfox/koa-es7-boilerplate) with this commit: https://github.com/unixfox/koa-es7-boilerplate/commit/515150de793cf8bae7fa584be98b8648c72c4921.
I removed the `loadModules` method and I tried to register manually the services and stores. Unfortunately I got this new error:
```
  17:37:36:476 DEBUG Creating server... (src/lib/server.js:24)
  17:37:36:482 DEBUG startup Server created, ready to listen (src/lib/server.js:61)
  17:37:36:486 DEBUG Server listening on 5000 in development mode (src/bin/www.js:9)
  17:37:37:611 ERROR Error in request (src/middleware/error-handler.js:20)
    →  AwilixResolutionError: Could not resolve 'find'.
    →  
    →  Resolution path: find
    →      at resolve (/tmp/koa-es7-boilerplate/node_modules/awilix/lib/container.js:239:23)
    →      at Object.get (/tmp/koa-es7-boilerplate/node_modules/awilix/lib/container.js:66:32)
    →      at Object.findTodos (file:///tmp/koa-es7-boilerplate/src/routes/todos-api.js:8:52)
    →      at memberInvoker (/tmp/koa-es7-boilerplate/node_modules/awilix-koa/lib/invokers.js:85:45)
    →      at dispatch (/tmp/koa-es7-boilerplate/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    →      at next (/tmp/koa-es7-boilerplate/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    →      at /tmp/koa-es7-boilerplate/node_modules/koa-router/lib/router.js:346:16
    →      at dispatch (/tmp/koa-es7-boilerplate/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    →      at /tmp/koa-es7-boilerplate/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    →      at dispatch (/tmp/koa-es7-boilerplate/node_modules/koa-router/lib/router.js:351:31)
```
It seems like todoService is not loaded properly but I don't understand why.

**Comment by jeffijoe** [comment]
Because by removing the options from `createContainer` you made it use `PROXY` mode instead of `CLASSIC`, so it was trying to resolve `TodoService.find` since it thinks `TodoService` is the cradle.

**Comment by unixfox** [comment]
Oh right! I forgot about that.

Thank you so much for your help!

I was able to remove completely babel and restore the functionality where you can load multiple routes, services and stores at the same time just by specifying the directory name.   
I pushed the changes in this commit: https://github.com/unixfox/koa-es7-boilerplate/commit/b3d2eb59c513ea82c38773a8723ffc41ddac5f2d   
Do note that it's not clean code at the moment because I was just testing if I was able to come up with a similar functionality.

For now, I'll close this issue because it's solved for me.
