### ISSUE TITLE
Using this boilerplate as Mobile App backend

### ISSUE THREAD

**Issue by Rajan** [jeffijoe/koa-es7-boilerplate#3]
Does it support passport or jwt etc. for mobile based auth?
Thank you in advance.

**Comment by jeffijoe** [comment]
Yes, its actually an API boilerplate.

~ Jeff Hansen

**Comment by Rajan** [comment]
I'm confused between this and glazed.
This is too little and glazed is too much.
https://github.com/glazedio/glazed

**Comment by jeffijoe** [comment]
This is just a boilerplate with essentials like auto-loading controller files, managing environment variables, testing setup, and a simple DI setup.

Glazed seems like they're made all the choices for you.
