### ISSUE TITLE
Consider using babel-preset-env instead of specific year preset

### ISSUE THREAD

**Issue by brendanvinson** [jeffijoe/koa-es7-boilerplate#6]
I've switched to using [babel-preset-env](https://github.com/babel/babel-preset-env) and have it set up so it auto-detects what version of node I'm running and transpiles the code based on that. 

It feels easier and more dynamic than having to gauge what version of node supports what version of ecmascript and at what stage.

example `.babelrc`:
```
{
    "presets": [
        ["env", {
            "targets": {
                "node": "current"
            }
        }]
    ]
}
```

**Comment by jeffijoe** [comment]
Nice, I actually didn't know that existed!

I'm open to swapping out `es2015-node6` with `env`, however that does imply that you are _always_ running the same version of node locally as you are in production. Is this an assumption that is safe to make?

**Comment by brendanvinson** [comment]
I think it makes things more version agnostic. Assuming you're not porting your dist folder from development into production, it shouldn't matter as you're still developing in ES7 and it's figuring out what features to transpile on the backend based off node version support.

From the docs:

> Support a target option "node": "current" to compile for the currently running node version.
> 
> For example, if you are building on Node 4, arrow functions won't be converted, but they will if you build on Node 0.12.

**Comment by jeffijoe** [comment]
Oh yeah, come to think of it I usually do builds in docker anyway.

Yep, sounds good to me - if you're willing to do a PR you're more than welcome.

**Comment by brendanvinson** [comment]
One caveat is depending on which version of node you build in, you may need additional plugins, for instance my full babelrc file looks like:
```
{
    "presets": [
        ["env", {
            "targets": {
                "node": "current"
            }
        }]
    ],
    "plugins": [
        ["transform-object-rest-spread", { "useBuiltIns": true }]
    ]
}
```
For Node v6.9.5

If we're good with that, then we'll proceed.

**Comment by jeffijoe** [comment]
`transform-object-rest-spread` isn't in `es2015` anyway, is it? I believe thats stage 2, 3 or 4 which means that one is covered by `stage-2` which is in the boilerplate as well.

Or am I missing something?

**Comment by brendanvinson** [comment]
It looks like [stages aren't supported](https://github.com/babel/babel-preset-env/issues/14) in preset-env, only the things that are in [latest](http://babeljs.io/docs/plugins/preset-latest/).

**Comment by jeffijoe** [comment]
Right, but you can use more than 1 preset, which is what we're already doing:

```
"presets": ["es2015-node6", "stage-1"],
```

**Comment by brendanvinson** [comment]
Ah right, I get it now. No, you're not missing something, just wanted to make sure we're aware it's not a complete replacement.

**Comment by jeffijoe** [comment]
Ah, my bad, just read the link. Do they explicitly disable this?

In that case, to get async-await going and other things, we'd need to manually specify a lot of plugins. I don't think that's a good trade-off. Mind testing it out?

**Comment by brendanvinson** [comment]
Looks like es2017 supports async-to-generator so that's covered under preset-env.

I just transpiled a couple different ways (local `npm install` with babel transpile on postinstall and building in docker) using this syntax in my `.babelrc`:
```
{
    "presets": [
        ["env", {
            "targets": {
                "node": "current"
            }
        }],
        "stage-1"
    ]
}
```
and it built fine.

**Comment by jeffijoe** [comment]
Ah, so we would only need to add `transform-object-rest-spread`?

**Comment by jeffijoe** [comment]
With object spread and everything? If so, then I'm in.

**Comment by brendanvinson** [comment]
I use that particular plugin because that covers my specific use case, that being said I think we should go ahead and use `stage-1` until we're confident that the boilerplate doesn't use any other features that are needed.

**Comment by jeffijoe** [comment]
Yeah agreed, I'm always up for using as much native functionality as possible. Go ahead and submit a PR if you want, if not I'll do it whenever I'm free.

Make sure to run tests :shipit:

**Comment by brendanvinson** [comment]
For documentation purposes, it looks like what this is what's not supported in preset-env:

- transform-export-extensions (stage 1)
- transform-class-properties (stage 2)
- transform-object-rest-spread (stage 3)

**Comment by jeffijoe** [comment]
But adding `stage-1` remedies this, correct?

**Comment by brendanvinson** [comment]
Yes, that's correct. `stage-1` includes all stages.

**Comment by jeffijoe** [comment]
Great, just checking since [that link](https://github.com/babel/babel-preset-env/issues/14) had me worried.

Do you want to submit a PR?

**Comment by brendanvinson** [comment]
I can, yes.

**Comment by jeffijoe** [comment]
Ohhh hey you work at CoreLogic! Say hi to Jon West for me. 😄

**Comment by brendanvinson** [comment]
Will do, we're actually working on a project together that uses the boilerplate. 👍

**Comment by jeffijoe** [comment]
That's awesome!
