### ISSUE TITLE
nodemon multiple times when changes

### ISSUE THREAD

**Issue by JoaoPintoM** [jeffijoe/koa-es7-boilerplate#8]
Hello, 

I have an issue with the current configuration when running "npm run dev"

sometimes when i save, i get multiple times:
[nodemon] restarting due to changes...
[nodemon] starting `npm run babel-node src/bin/server.js`

which causes issues, sometimes it crash as the app continue to runs on the same port.. then i got an exception "already running on port 1338"

I don't have any clue how to fix that, it's difficult to work on the project as each time i save I need to find the process by pid and kill it.

lsof -i tcp:1338
to find the process.

If you have any ideas.

Kr,

**Comment by jeffijoe** [comment]
Are you using something like WebStorm or anything that will compile the files as you save? Because if you save a file, and your IDE compiles it for you and saves it to the same folder, then that triggers a change.

**Comment by JoaoPintoM** [comment]
No i'm using atom, i don't have any kind of integrated compiler. (thx for the fast answer)

it just happened again 2 min ago: 
[screenshot](https://gyazo.com/cb4b8cf812069b1221fc394611b15c5f)

**Comment by jeffijoe** [comment]
Try setting `"dev": "nodemon --delay 300 src src/bin/server.js"` in package.json, see if that helps.

I'm guessing you're on macOS like me, and I am not experiencing this issue at all. 🤔

**Comment by JoaoPintoM** [comment]
Ok thx it helps ! I'have tried to crash the app by spam save and for the moment it did not crash. 

I have just modified it cause --delay by default works with seconds:

solution:

-> nodemon --delay 500ms src/bin/server.js

**Comment by jeffijoe** [comment]
Ah, my bad - I still think there's some watching compiler going, else it wouldn't trigger a change like that. I think Atom has it, too - you might have enabled it without knowing.
